# Generated by Django 2.2.3 on 2019-07-22 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0004_auto_20190721_2033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionario',
            old_name='empresas',
            new_name='empresa',
        ),
    ]
